services:
  node-api:
    container_name: notifications-app
    ports:
      - "3000:3000"
    image: notifications-server
    build: ./
    networks:
      - notifications-network
    environment:
      - NODE_ENV=test
      - MONGODB_URI=mongodb://notifications-mongo-db:27017
  mongo-db:
    image: mongo
    container_name: notifications-mongo-db
    ports:
      - "27017:27017"
    networks:
      - notifications-network
networks:
  notifications-network:
    name: notifications-network
    driver: bridge
